FROM python:3.11

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

COPY Systems/PhotoSearch/LostAnimals.PhotoSearch/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY Systems/PhotoSearch/LostAnimals.PhotoSearch/ .

RUN ls -la

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]