version: '3.8'

services:
  lostanimals_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "45432:5432"
    networks:
      - shared_lostanimals_net
    volumes:
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - shared_lostanimals_net

  milvus:
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - milvusdata:/var/lib/milvus
    networks:
      - shared_lostanimals_net

  lostanimals_api:
    ports:
      - "10000:8080"
    networks:
      - shared_lostanimals_net
    env_file:
      - env.api
    volumes:
      - ./images/dataset:/app/images/dataset
      - storage:/app/storage

  lostanimals_identity:
    ports:
      - "10001:8080"
    networks:
      - shared_lostanimals_net
    env_file:
      - env.identity

  lostanimals_web:
    ports:
      - "10002:80"
    networks:
      - shared_lostanimals_net

  animal_photosearch_api:
    ports:
      - "10003:8000"
    networks:
      - shared_lostanimals_net
    env_file:
      - env.photosearch
    volumes:
      - ./images/dataset:/app/images/dataset
      - storage:/app/storage