version: '3.8'

services:
  lostanimals_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "45432:5432"
    networks:
      - shared_lostanimals_net
    volumes:
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672" 
    networks:
      - shared_lostanimals_net

  etcd:
    container_name: milvus-etcd
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - etcd_data:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - shared_lostanimals_net

  minio:
    container_name: milvus-minio
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - minio_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - shared_lostanimals_net

  milvus:
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - MINIO_ADDRESS=minio:9000
    volumes:
      - milvusdata:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - etcd
      - minio
    networks:
      - shared_lostanimals_net

  lostanimals_api:
    ports:
      - "10000:8080"
    networks:
      - shared_lostanimals_net
    env_file:
      - env.api
    volumes:
      - ./images/dataset:/app/images/dataset
      - storage:/app/storage

  lostanimals_identity:
    ports:
      - "10001:8080"
    networks:
      - shared_lostanimals_net
    env_file:
      - env.identity

  lostanimals_web:
    ports:
      - "10002:80"
    networks:
      - shared_lostanimals_net

  animal_photosearch_api:
    ports:
      - "10003:8000"
    networks:
      - shared_lostanimals_net
    env_file:
      - env.photosearch
    volumes:
      - ./images/dataset:/app/images/dataset
      - storage:/app/storage
    depends_on:
      - rabbitmq
      - milvus
      - etcd
      - minio