// <auto-generated />
using System;
using LostAnimals.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LostAnimals.Context.Migrations.MSSQL.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20240222174238_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LostAnimals.Context.Entities.AnimalKind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnimalKindName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("animal_kinds", (string)null);
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.Breed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnimalKindID")
                        .HasColumnType("int");

                    b.Property<string>("BreedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AnimalKindID");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("breeds", (string)null);
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2024, 2, 22, 20, 42, 38, 319, DateTimeKind.Local).AddTicks(1831));

                    b.Property<int>("NoteID")
                        .HasColumnType("int");

                    b.Property<int?>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<int>("PhotoGalleryID")
                        .HasColumnType("int");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AttributeID");

                    b.HasIndex("NoteID");

                    b.HasIndex("ParentCommentId")
                        .IsUnique()
                        .HasFilter("[ParentCommentId] IS NOT NULL");

                    b.HasIndex("PhotoGalleryID");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("comments", (string)null);
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.CommentAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("comment_attributes", (string)null);
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnimalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BreedID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("LastSeenDate")
                        .HasColumnType("date");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longtitude")
                        .HasColumnType("float");

                    b.Property<int?>("PhotoGalleryID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BreedID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("PhotoGalleryID");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("notes", (string)null);
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.NoteCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("note_categories", (string)null);
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.PhotoGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("photo_gallery", (string)null);
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.PhotoStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PhotoFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhotoGalleryID")
                        .HasColumnType("int");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PhotoGalleryID");

                    b.HasIndex("Uid")
                        .IsUnique();

                    b.ToTable("photo_storage", (string)null);
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.Breed", b =>
                {
                    b.HasOne("LostAnimals.Context.Entities.AnimalKind", "AnimalKind")
                        .WithMany("Breeds")
                        .HasForeignKey("AnimalKindID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalKind");
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.Comment", b =>
                {
                    b.HasOne("LostAnimals.Context.Entities.CommentAttribute", "Attribute")
                        .WithMany("Comments")
                        .HasForeignKey("AttributeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostAnimals.Context.Entities.Note", "Note")
                        .WithMany("Comments")
                        .HasForeignKey("NoteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LostAnimals.Context.Entities.Comment", "ParentComment")
                        .WithOne()
                        .HasForeignKey("LostAnimals.Context.Entities.Comment", "ParentCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("LostAnimals.Context.Entities.PhotoGallery", "PhotoGallery")
                        .WithMany("Comments")
                        .HasForeignKey("PhotoGalleryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Attribute");

                    b.Navigation("Note");

                    b.Navigation("ParentComment");

                    b.Navigation("PhotoGallery");
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.Note", b =>
                {
                    b.HasOne("LostAnimals.Context.Entities.Breed", "Breed")
                        .WithMany("Notes")
                        .HasForeignKey("BreedID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostAnimals.Context.Entities.NoteCategory", "Category")
                        .WithMany("Notes")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LostAnimals.Context.Entities.PhotoGallery", "PhotoGallery")
                        .WithMany("Notes")
                        .HasForeignKey("PhotoGalleryID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Breed");

                    b.Navigation("Category");

                    b.Navigation("PhotoGallery");
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.PhotoStorage", b =>
                {
                    b.HasOne("LostAnimals.Context.Entities.PhotoGallery", "PhotoGallery")
                        .WithMany("PhotoStorages")
                        .HasForeignKey("PhotoGalleryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhotoGallery");
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.AnimalKind", b =>
                {
                    b.Navigation("Breeds");
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.Breed", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.CommentAttribute", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.Note", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.NoteCategory", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("LostAnimals.Context.Entities.PhotoGallery", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Notes");

                    b.Navigation("PhotoStorages");
                });
#pragma warning restore 612, 618
        }
    }
}
